# Generated by Django 4.0.4 on 2022-05-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('abbr', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('main_income', models.CharField(blank=True, max_length=255, null=True)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('staffs', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('book', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('job_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('main_duty', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mysite_echarts_list',
                'managed': True,
            },
        ),
    ]
